services:
  nginx:
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: "Dockerfile"
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    pull_policy: never
    restart: always
  
  wordpress:
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: "Dockerfile"
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADM_USER: ${WORDPRESS_ADM_USER}
      WORDPRESS_ADM_PASS: ${WORDPRESS_ADM_PASS}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    pull_policy: never
    restart: always

  mariadb:
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    build: 
      context: requirements/mariadb
      dockerfile: "Dockerfile"
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    pull_policy: never
    restart: always
  
  redis:
    networks:
      - inception
    build: 
      context: requirements/bonus/redis
      dockerfile: "Dockerfile"
    container_name: redis
    pull_policy: never
    restart: always
  
  ftp:
    networks:
      - inception
    build:
      context: requirements/bonus/ftp
      dockerfile: "Dockerfile"
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
        FTP_ROOT: ${FTP_ROOT}
    container_name: ftp
    pull_policy: never
    volumes:
      - web:/web_data
    ports:
      - "20-21:20-21"
      - "30000-30100:30000-30100"
    restart: always

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/web
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

networks:
  inception:
    driver: bridge