services:
  nginx:
    networks:
      - inception
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    restart: always
  
  wordpress:
    networks:
      - inception
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADM_USER: ${WORDPRESS_ADM_USER}
      WORDPRESS_ADM_PASS: ${WORDPRESS_ADM_PASS}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    restart: always

  mariadb:
    networks:
      - inception
    build: requirements/mariadb/.
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    restart: always

networks:
  inception:
    driver: bridge